spring:
  application:
    name: client
server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true